package com.example.firstapp;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.AutoCompleteTextView;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Spinner;
import android.widget.TextView;
import android.widget.Toast;

import com.google.android.gms.auth.api.signin.GoogleSignIn;
import com.google.android.gms.auth.api.signin.GoogleSignInAccount;
import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.OnFailureListener;
import com.google.android.gms.tasks.OnSuccessListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.Query;
import com.google.firebase.database.ValueEventListener;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Random;
import java.util.Timer;
import java.util.TimerTask;

import static android.app.PendingIntent.getActivity;

public class gencode extends AppCompatActivity {
    //define variables with the type to be used
    private Timer splashTimer;
    private static final long DELAY=30000;
    private boolean scheduled=false;
    TextView tvg;
    Button b;
    EditText subj;
    Spinner spinner;
    AutoCompleteTextView autoCompleteTextView;
    private FirebaseAuth mFirebaseauth;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_gencode);

        //gide action bar
        getSupportActionBar().hide();



        //instantiate the variables
        tvg = findViewById(R.id.txt);
        b = findViewById(R.id.gen);
        subj=findViewById(R.id.subject);

        /* spinner = (Spinner) findViewById(R.id.spinner);
// Create an ArrayAdapter using the string array and a default spinner layout
        ArrayAdapter<CharSequence> adapter = ArrayAdapter.createFromResource(this,
                R.array.all_subs, android.R.layout.simple_spinner_item);
// Specify the layout to use when the list of choices appears
        adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
// Apply the adapter to the spinner
        spinner.setAdapter(adapter);*/

       /* spinner=findViewById(R.id.spinner);
        String[] items={"nlp","dip","cs","ps","dm","st"};
        ArrayAdapter arrayAdapter=new ArrayAdapter(getApplicationContext(),R.layout.support_simple_spinner_dropdown_item,items);
        spinner.setAdapter(arrayAdapter); */

        mFirebaseauth= FirebaseAuth.getInstance();

    b.setOnClickListener(new View.OnClickListener() {
        @Override
        public void onClick(View v) {

            //method calling
            gencod();
        }
    });
    }

    //method definition
    private void gencod() {
        TextView tvg;
        tvg = findViewById(R.id.txt);
        EditText ets;
        ets=findViewById(R.id.subject);
        String sub=ets.getText().toString();

        if(sub.equals("nlp") || sub.equals("dip") || sub.equals("cs") || sub.equals("ps") || sub.equals("st") || sub.equals("dm")) {
            //to store the code generated by the method getrandomstring into code
            String code = getRandomString(6);

            //display the code generated
            tvg.setText(code);
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy.MM.dd 'at' HH:mm:ss");                          //pattern "yyyy.MM.dd G 'at' HH:mm:ss Z" op:- 2021.04.27 AD at 17:03:30 +0530
            String cdt = sdf.format(new Date());

            String url = "https://firstapp-70022-default-rtdb.asia-southeast1.firebasedatabase.app/";
            FirebaseDatabase firebaseDatabase = FirebaseDatabase.getInstance(url);

            //create hash to store the data
            HashMap<String, Object> tempmap = new HashMap<>();                             //temp value
            tempmap.put("temp", code);
            FirebaseDatabase.getInstance(url).getReference("tempk8").setValue(tempmap);

            //calling of a method to upload the data i.e., code generated
            uploadcode(code, cdt);

            //method calling for the timer
            stoptimer();
        }
        else{
            Toast.makeText(getApplicationContext(),"invalid subject id",Toast.LENGTH_SHORT).show();
        }
    }

    //method to get random string
    public static String getRandomString(int i) {
        final String chara = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        StringBuilder result = new StringBuilder();
        while (i > 0) {
            Random rand = new Random();
            result.append(chara.charAt(rand.nextInt(chara.length())));
            i--;
        }
        //returns the resultant string
        return result.toString();
    }


    //the timer for the validity of the code generated
    private void stoptimer() {
        splashTimer=new Timer();
        splashTimer.schedule(new TimerTask() {
            @Override
            public void run() {
                HashMap<String,Object> tempmap=new HashMap<>();                             //temp value
                tempmap.put("temp","  ");
                String url="https://firstapp-70022-default-rtdb.asia-southeast1.firebasedatabase.app/";
                FirebaseDatabase.getInstance(url).getReference("tempk8").setValue(tempmap);
            }
        },DELAY);
        scheduled=true;
    }

    //code to upload the code generated
    private void uploadcode(final String code, String cdt) {
        subj=findViewById(R.id.subject);
        String sub=subj.getText().toString();
        final String url = "https://firstapp-70022-default-rtdb.asia-southeast1.firebasedatabase.app/";
        FirebaseDatabase firebaseDatabase = FirebaseDatabase.getInstance(url);

        //create hash map to store data
       final HashMap<String,Object> map=new HashMap<>();
        map.put("code",cdt);
        map.put("subject",sub);

        firebaseDatabase.getReference("k8").addListenerForSingleValueEvent(new ValueEventListener() {
            @Override
            public void onDataChange(@NonNull DataSnapshot snapshot) {
                if (snapshot.hasChild(code)) {
                    //if already code exists of the one generated in the database
                    gencod();
                }
                //if doesn't exist
                else {
                    //to set the value of code in the database
                    FirebaseDatabase.getInstance(url).getReference("k8").child(code)
                            .setValue(map)
                            .addOnCompleteListener(new OnCompleteListener<Void>() {
                                @Override
                                public void onComplete(@NonNull Task<Void> task) {
                                    Log.i("hikj", "onComplete");
                                }
                            }).addOnFailureListener(new OnFailureListener() {
                        @Override
                        public void onFailure(@NonNull Exception e) {
                            Log.i("hikj", "onFailure" + e.toString());
                            Toast.makeText(gencode.this, "error" + e, Toast.LENGTH_SHORT).show();
                        }
                    }).addOnSuccessListener(new OnSuccessListener<Void>() {
                        @Override
                        public void onSuccess(Void aVoid) {
                            Log.i("hikj", "On Success");
                        }
                    });
                }
            }
            @Override
            public void onCancelled(@NonNull DatabaseError error) {

            }
        });
    }

    //to get records of the attendance
    public void getrec(View view) {
            Intent intent=new Intent(getApplicationContext(),getrecords.class);
            startActivity(intent);
    }

    //method to signout
    public void signout(View view) {
        FirebaseUser mfirebaseuser= mFirebaseauth.getCurrentUser();
        mFirebaseauth.signOut();
        Intent i=new Intent(gencode.this,Main2Activity.class);
        startActivity(i);
        finish();
    }
//method to add students attendance
    public void add_students(View view) {
        String codesend=tvg.getText().toString().trim();

        Intent i=new Intent(getApplicationContext(),addstu.class);
        i.putExtra("codeg",codesend);
        startActivity(i);
    }

//method to get percentage of every student
    public void getper(View view) {
        subj = findViewById(R.id.subject);
        String sub = subj.getText().toString().trim();
        if (sub.isEmpty()) {
            Toast.makeText(gencode.this, "enter subcode", Toast.LENGTH_SHORT).show();
        } else if (sub.equals("nlp") || sub.equals("dip") || sub.equals("cs") || sub.equals("ps") || sub.equals("st") || sub.equals("dm")) {
            Intent i = new Intent(getApplicationContext(), facper.class);
            i.putExtra("subcode", sub);
            startActivity(i);
        }
        else{
            Toast.makeText(gencode.this, "invalid subject code", Toast.LENGTH_SHORT).show();
        }
    }
}